fix issue 120
correlation-one/C1GamesStarterKit pull request #122
Opened 2022-03-24 14:52 UTC by WhymustIhaveaname

See https://github.com/correlation-one/C1GamesStarterKit/issues/120

2022-03-24 21:18 UTC, Ryan-McPartlan approved these changes

2022-03-24 21:19 UTC, Ryan-McPartlan requested changes
Hmmm, looks like there were some unexpected changes to some of the scripts

2022-03-25 04:22 UTC, WhymustIhaveaname commented
It was automatically done by git. When I just cloned the repo and did nothing
```
$ git add -uv
warning: CRLF will be replaced by LF in scripts/test_algo_linux.
The file will have its original line endings in your working directory
add 'scripts/test_algo_linux'
warning: CRLF will be replaced by LF in scripts/test_algo_mac.
The file will have its original line endings in your working directory
add 'scripts/test_algo_mac'
```

This is because the line endings in Windows and Unix-like systems are different. It seems that the authors were using Windows while I am using Linux (Fedora 33). As these two files are for Linux and Mac, I think it is better to do it the Linux way. The windows developers can change the line endings settings in their IDE.

Please don't worry, it (the changes) works on my Linux.
```
$ ./test_algo_linux ../python-algo/
Running algo at: "../python-algo/"
Using replay: "/home/r75800x/Public/C1GamesStarterKit/scripts/test_replay.replay"
Running command: "../python-algo/run.sh"
Random seed: 527125338918096743
---------------- Starting Your Algo --------------------
Got end state, game over. Stopping algo.
```

2022-03-25 04:28 UTC, WhymustIhaveaname commented
Anyway, I decided to not touch that two binary files. I created a new PR https://github.com/correlation-one/C1GamesStarterKit/pull/123

2022-03-25 04:28 UTC, closed without merging